// Code generated by protoc-gen-go. DO NOT EDIT.
// source: major.proto

package majorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Major struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level                string   `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Head                 string   `protobuf:"bytes,4,opt,name=head,proto3" json:"head,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Major) Reset()         { *m = Major{} }
func (m *Major) String() string { return proto.CompactTextString(m) }
func (*Major) ProtoMessage()    {}
func (*Major) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{0}
}

func (m *Major) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Major.Unmarshal(m, b)
}
func (m *Major) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Major.Marshal(b, m, deterministic)
}
func (m *Major) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Major.Merge(m, src)
}
func (m *Major) XXX_Size() int {
	return xxx_messageInfo_Major.Size(m)
}
func (m *Major) XXX_DiscardUnknown() {
	xxx_messageInfo_Major.DiscardUnknown(m)
}

var xxx_messageInfo_Major proto.InternalMessageInfo

func (m *Major) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Major) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Major) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Major) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *Major) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListMajorReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMajorReq) Reset()         { *m = ListMajorReq{} }
func (m *ListMajorReq) String() string { return proto.CompactTextString(m) }
func (*ListMajorReq) ProtoMessage()    {}
func (*ListMajorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{1}
}

func (m *ListMajorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMajorReq.Unmarshal(m, b)
}
func (m *ListMajorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMajorReq.Marshal(b, m, deterministic)
}
func (m *ListMajorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMajorReq.Merge(m, src)
}
func (m *ListMajorReq) XXX_Size() int {
	return xxx_messageInfo_ListMajorReq.Size(m)
}
func (m *ListMajorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMajorReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListMajorReq proto.InternalMessageInfo

type ListMajorRes struct {
	Major                []*Major `protobuf:"bytes,1,rep,name=major,proto3" json:"major,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMajorRes) Reset()         { *m = ListMajorRes{} }
func (m *ListMajorRes) String() string { return proto.CompactTextString(m) }
func (*ListMajorRes) ProtoMessage()    {}
func (*ListMajorRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{2}
}

func (m *ListMajorRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMajorRes.Unmarshal(m, b)
}
func (m *ListMajorRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMajorRes.Marshal(b, m, deterministic)
}
func (m *ListMajorRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMajorRes.Merge(m, src)
}
func (m *ListMajorRes) XXX_Size() int {
	return xxx_messageInfo_ListMajorRes.Size(m)
}
func (m *ListMajorRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMajorRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListMajorRes proto.InternalMessageInfo

func (m *ListMajorRes) GetMajor() []*Major {
	if m != nil {
		return m.Major
	}
	return nil
}

type ReadMajorReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMajorReq) Reset()         { *m = ReadMajorReq{} }
func (m *ReadMajorReq) String() string { return proto.CompactTextString(m) }
func (*ReadMajorReq) ProtoMessage()    {}
func (*ReadMajorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{3}
}

func (m *ReadMajorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMajorReq.Unmarshal(m, b)
}
func (m *ReadMajorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMajorReq.Marshal(b, m, deterministic)
}
func (m *ReadMajorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMajorReq.Merge(m, src)
}
func (m *ReadMajorReq) XXX_Size() int {
	return xxx_messageInfo_ReadMajorReq.Size(m)
}
func (m *ReadMajorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMajorReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMajorReq proto.InternalMessageInfo

func (m *ReadMajorReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadMajorRes struct {
	Major                *Major   `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMajorRes) Reset()         { *m = ReadMajorRes{} }
func (m *ReadMajorRes) String() string { return proto.CompactTextString(m) }
func (*ReadMajorRes) ProtoMessage()    {}
func (*ReadMajorRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{4}
}

func (m *ReadMajorRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMajorRes.Unmarshal(m, b)
}
func (m *ReadMajorRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMajorRes.Marshal(b, m, deterministic)
}
func (m *ReadMajorRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMajorRes.Merge(m, src)
}
func (m *ReadMajorRes) XXX_Size() int {
	return xxx_messageInfo_ReadMajorRes.Size(m)
}
func (m *ReadMajorRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMajorRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMajorRes proto.InternalMessageInfo

func (m *ReadMajorRes) GetMajor() *Major {
	if m != nil {
		return m.Major
	}
	return nil
}

type CreateMajorReq struct {
	Major                *Major   `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMajorReq) Reset()         { *m = CreateMajorReq{} }
func (m *CreateMajorReq) String() string { return proto.CompactTextString(m) }
func (*CreateMajorReq) ProtoMessage()    {}
func (*CreateMajorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{5}
}

func (m *CreateMajorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMajorReq.Unmarshal(m, b)
}
func (m *CreateMajorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMajorReq.Marshal(b, m, deterministic)
}
func (m *CreateMajorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMajorReq.Merge(m, src)
}
func (m *CreateMajorReq) XXX_Size() int {
	return xxx_messageInfo_CreateMajorReq.Size(m)
}
func (m *CreateMajorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMajorReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMajorReq proto.InternalMessageInfo

func (m *CreateMajorReq) GetMajor() *Major {
	if m != nil {
		return m.Major
	}
	return nil
}

type CreateMajorRes struct {
	Major                *Major   `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMajorRes) Reset()         { *m = CreateMajorRes{} }
func (m *CreateMajorRes) String() string { return proto.CompactTextString(m) }
func (*CreateMajorRes) ProtoMessage()    {}
func (*CreateMajorRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{6}
}

func (m *CreateMajorRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMajorRes.Unmarshal(m, b)
}
func (m *CreateMajorRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMajorRes.Marshal(b, m, deterministic)
}
func (m *CreateMajorRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMajorRes.Merge(m, src)
}
func (m *CreateMajorRes) XXX_Size() int {
	return xxx_messageInfo_CreateMajorRes.Size(m)
}
func (m *CreateMajorRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMajorRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMajorRes proto.InternalMessageInfo

func (m *CreateMajorRes) GetMajor() *Major {
	if m != nil {
		return m.Major
	}
	return nil
}

type UpdateMajorReq struct {
	Major                *Major   `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMajorReq) Reset()         { *m = UpdateMajorReq{} }
func (m *UpdateMajorReq) String() string { return proto.CompactTextString(m) }
func (*UpdateMajorReq) ProtoMessage()    {}
func (*UpdateMajorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{7}
}

func (m *UpdateMajorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMajorReq.Unmarshal(m, b)
}
func (m *UpdateMajorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMajorReq.Marshal(b, m, deterministic)
}
func (m *UpdateMajorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMajorReq.Merge(m, src)
}
func (m *UpdateMajorReq) XXX_Size() int {
	return xxx_messageInfo_UpdateMajorReq.Size(m)
}
func (m *UpdateMajorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMajorReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMajorReq proto.InternalMessageInfo

func (m *UpdateMajorReq) GetMajor() *Major {
	if m != nil {
		return m.Major
	}
	return nil
}

type UpdateMajorRes struct {
	Major                *Major   `protobuf:"bytes,1,opt,name=major,proto3" json:"major,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMajorRes) Reset()         { *m = UpdateMajorRes{} }
func (m *UpdateMajorRes) String() string { return proto.CompactTextString(m) }
func (*UpdateMajorRes) ProtoMessage()    {}
func (*UpdateMajorRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{8}
}

func (m *UpdateMajorRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMajorRes.Unmarshal(m, b)
}
func (m *UpdateMajorRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMajorRes.Marshal(b, m, deterministic)
}
func (m *UpdateMajorRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMajorRes.Merge(m, src)
}
func (m *UpdateMajorRes) XXX_Size() int {
	return xxx_messageInfo_UpdateMajorRes.Size(m)
}
func (m *UpdateMajorRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMajorRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMajorRes proto.InternalMessageInfo

func (m *UpdateMajorRes) GetMajor() *Major {
	if m != nil {
		return m.Major
	}
	return nil
}

type DeleteMajorReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMajorReq) Reset()         { *m = DeleteMajorReq{} }
func (m *DeleteMajorReq) String() string { return proto.CompactTextString(m) }
func (*DeleteMajorReq) ProtoMessage()    {}
func (*DeleteMajorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{9}
}

func (m *DeleteMajorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMajorReq.Unmarshal(m, b)
}
func (m *DeleteMajorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMajorReq.Marshal(b, m, deterministic)
}
func (m *DeleteMajorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMajorReq.Merge(m, src)
}
func (m *DeleteMajorReq) XXX_Size() int {
	return xxx_messageInfo_DeleteMajorReq.Size(m)
}
func (m *DeleteMajorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMajorReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMajorReq proto.InternalMessageInfo

func (m *DeleteMajorReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteMajorRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMajorRes) Reset()         { *m = DeleteMajorRes{} }
func (m *DeleteMajorRes) String() string { return proto.CompactTextString(m) }
func (*DeleteMajorRes) ProtoMessage()    {}
func (*DeleteMajorRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_685540edb659e78a, []int{10}
}

func (m *DeleteMajorRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMajorRes.Unmarshal(m, b)
}
func (m *DeleteMajorRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMajorRes.Marshal(b, m, deterministic)
}
func (m *DeleteMajorRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMajorRes.Merge(m, src)
}
func (m *DeleteMajorRes) XXX_Size() int {
	return xxx_messageInfo_DeleteMajorRes.Size(m)
}
func (m *DeleteMajorRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMajorRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMajorRes proto.InternalMessageInfo

func (m *DeleteMajorRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Major)(nil), "major.Major")
	proto.RegisterType((*ListMajorReq)(nil), "major.ListMajorReq")
	proto.RegisterType((*ListMajorRes)(nil), "major.ListMajorRes")
	proto.RegisterType((*ReadMajorReq)(nil), "major.ReadMajorReq")
	proto.RegisterType((*ReadMajorRes)(nil), "major.ReadMajorRes")
	proto.RegisterType((*CreateMajorReq)(nil), "major.CreateMajorReq")
	proto.RegisterType((*CreateMajorRes)(nil), "major.CreateMajorRes")
	proto.RegisterType((*UpdateMajorReq)(nil), "major.UpdateMajorReq")
	proto.RegisterType((*UpdateMajorRes)(nil), "major.UpdateMajorRes")
	proto.RegisterType((*DeleteMajorReq)(nil), "major.DeleteMajorReq")
	proto.RegisterType((*DeleteMajorRes)(nil), "major.DeleteMajorRes")
}

func init() { proto.RegisterFile("major.proto", fileDescriptor_685540edb659e78a) }

var fileDescriptor_685540edb659e78a = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x6d, 0xd2, 0xa6, 0xfd, 0x7a, 0x89, 0x32, 0xdc, 0x07, 0xc8, 0xca, 0x80, 0x2a, 0x4f, 0x15,
	0x43, 0x87, 0x82, 0xc4, 0xd4, 0x05, 0x18, 0x61, 0x09, 0x62, 0x61, 0x73, 0x9b, 0x93, 0x08, 0x6a,
	0x49, 0x88, 0xd3, 0xfe, 0x3b, 0xfe, 0x1b, 0x8a, 0xe3, 0x5a, 0x76, 0x14, 0xa4, 0xaa, 0xdb, 0xdd,
	0xf3, 0xbb, 0x7b, 0x2f, 0xcf, 0x0e, 0x84, 0x3b, 0xf1, 0x59, 0x54, 0x8b, 0xb2, 0x2a, 0xea, 0x02,
	0x03, 0xd5, 0xf0, 0x1d, 0x04, 0x2f, 0x4d, 0x81, 0x31, 0xf8, 0x79, 0xc6, 0xbc, 0x99, 0x37, 0x9f,
	0xa6, 0x7e, 0x9e, 0x21, 0xc2, 0xe8, 0x4b, 0xec, 0x88, 0xf9, 0x0a, 0x51, 0x35, 0x5e, 0x40, 0xb0,
	0xa5, 0x03, 0x6d, 0xd9, 0x50, 0x81, 0x6d, 0xd3, 0x30, 0x3f, 0x48, 0x64, 0x6c, 0xd4, 0x32, 0x9b,
	0x1a, 0xaf, 0x60, 0x2c, 0x6b, 0x51, 0xef, 0x25, 0x0b, 0x14, 0xaa, 0x3b, 0x1e, 0x43, 0xf4, 0x9c,
	0xcb, 0x5a, 0x49, 0xa6, 0xf4, 0xcd, 0x97, 0x4e, 0x2f, 0x91, 0x43, 0xeb, 0x8b, 0x79, 0xb3, 0xe1,
	0x3c, 0x5c, 0x46, 0x8b, 0xd6, 0x72, 0x7b, 0xae, 0x2d, 0x5f, 0x43, 0x94, 0x92, 0xc8, 0x8e, 0x3b,
	0xba, 0xce, 0x9b, 0x9d, 0xd6, 0xb9, 0xb3, 0xd3, 0xfb, 0x6b, 0xe7, 0x1d, 0xc4, 0x8f, 0x15, 0x89,
	0x9a, 0xcc, 0xd6, 0x73, 0xa6, 0x4e, 0xd6, 0x7a, 0x2b, 0xb3, 0x33, 0xb4, 0x9c, 0xa9, 0xd3, 0xb4,
	0x66, 0x10, 0x3f, 0xd1, 0x96, 0x2c, 0xad, 0x6e, 0x5a, 0x37, 0x1d, 0x86, 0x44, 0x06, 0x13, 0xb9,
	0xdf, 0x6c, 0x48, 0x4a, 0x45, 0xfb, 0x97, 0x1e, 0xdb, 0xe5, 0x8f, 0x0f, 0x91, 0xa2, 0xbd, 0x52,
	0x75, 0xc8, 0x37, 0x84, 0x2b, 0x08, 0xad, 0x00, 0xf0, 0x52, 0x5b, 0x70, 0xa3, 0x4c, 0x7a, 0x61,
	0xc9, 0x07, 0x78, 0x0f, 0x53, 0x73, 0x53, 0xf8, 0x5f, 0xb3, 0xec, 0xbb, 0x4d, 0x7a, 0xc0, 0x66,
	0x70, 0x05, 0xa1, 0x15, 0x86, 0xd1, 0x75, 0x63, 0x4d, 0x7a, 0x61, 0x3d, 0x6e, 0x7d, 0xb3, 0x19,
	0x77, 0x93, 0x4a, 0x7a, 0x61, 0x6d, 0xdb, 0x3c, 0x5a, 0x63, 0xdb, 0x7e, 0xd6, 0x49, 0x0f, 0x28,
	0xf9, 0xe0, 0x61, 0xfa, 0x3e, 0x51, 0x78, 0xb9, 0x5e, 0x8f, 0xd5, 0x5f, 0x78, 0xfb, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xd7, 0x81, 0x1a, 0x4b, 0x94, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MajorServiceClient is the client API for MajorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MajorServiceClient interface {
	CreateMajor(ctx context.Context, in *CreateMajorReq, opts ...grpc.CallOption) (*CreateMajorRes, error)
	ReadMajor(ctx context.Context, in *ReadMajorReq, opts ...grpc.CallOption) (*ReadMajorRes, error)
	UpdateMajor(ctx context.Context, in *UpdateMajorReq, opts ...grpc.CallOption) (*UpdateMajorRes, error)
	DeleteMajor(ctx context.Context, in *DeleteMajorReq, opts ...grpc.CallOption) (*DeleteMajorRes, error)
	ListMajor(ctx context.Context, in *ListMajorReq, opts ...grpc.CallOption) (*ListMajorRes, error)
}

type majorServiceClient struct {
	cc *grpc.ClientConn
}

func NewMajorServiceClient(cc *grpc.ClientConn) MajorServiceClient {
	return &majorServiceClient{cc}
}

func (c *majorServiceClient) CreateMajor(ctx context.Context, in *CreateMajorReq, opts ...grpc.CallOption) (*CreateMajorRes, error) {
	out := new(CreateMajorRes)
	err := c.cc.Invoke(ctx, "/major.MajorService/CreateMajor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *majorServiceClient) ReadMajor(ctx context.Context, in *ReadMajorReq, opts ...grpc.CallOption) (*ReadMajorRes, error) {
	out := new(ReadMajorRes)
	err := c.cc.Invoke(ctx, "/major.MajorService/ReadMajor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *majorServiceClient) UpdateMajor(ctx context.Context, in *UpdateMajorReq, opts ...grpc.CallOption) (*UpdateMajorRes, error) {
	out := new(UpdateMajorRes)
	err := c.cc.Invoke(ctx, "/major.MajorService/UpdateMajor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *majorServiceClient) DeleteMajor(ctx context.Context, in *DeleteMajorReq, opts ...grpc.CallOption) (*DeleteMajorRes, error) {
	out := new(DeleteMajorRes)
	err := c.cc.Invoke(ctx, "/major.MajorService/DeleteMajor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *majorServiceClient) ListMajor(ctx context.Context, in *ListMajorReq, opts ...grpc.CallOption) (*ListMajorRes, error) {
	out := new(ListMajorRes)
	err := c.cc.Invoke(ctx, "/major.MajorService/ListMajor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MajorServiceServer is the server API for MajorService service.
type MajorServiceServer interface {
	CreateMajor(context.Context, *CreateMajorReq) (*CreateMajorRes, error)
	ReadMajor(context.Context, *ReadMajorReq) (*ReadMajorRes, error)
	UpdateMajor(context.Context, *UpdateMajorReq) (*UpdateMajorRes, error)
	DeleteMajor(context.Context, *DeleteMajorReq) (*DeleteMajorRes, error)
	ListMajor(context.Context, *ListMajorReq) (*ListMajorRes, error)
}

// UnimplementedMajorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMajorServiceServer struct {
}

func (*UnimplementedMajorServiceServer) CreateMajor(ctx context.Context, req *CreateMajorReq) (*CreateMajorRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMajor not implemented")
}
func (*UnimplementedMajorServiceServer) ReadMajor(ctx context.Context, req *ReadMajorReq) (*ReadMajorRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadMajor not implemented")
}
func (*UnimplementedMajorServiceServer) UpdateMajor(ctx context.Context, req *UpdateMajorReq) (*UpdateMajorRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMajor not implemented")
}
func (*UnimplementedMajorServiceServer) DeleteMajor(ctx context.Context, req *DeleteMajorReq) (*DeleteMajorRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMajor not implemented")
}
func (*UnimplementedMajorServiceServer) ListMajor(ctx context.Context, req *ListMajorReq) (*ListMajorRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMajor not implemented")
}

func RegisterMajorServiceServer(s *grpc.Server, srv MajorServiceServer) {
	s.RegisterService(&_MajorService_serviceDesc, srv)
}

func _MajorService_CreateMajor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMajorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MajorServiceServer).CreateMajor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/major.MajorService/CreateMajor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MajorServiceServer).CreateMajor(ctx, req.(*CreateMajorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MajorService_ReadMajor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMajorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MajorServiceServer).ReadMajor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/major.MajorService/ReadMajor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MajorServiceServer).ReadMajor(ctx, req.(*ReadMajorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MajorService_UpdateMajor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMajorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MajorServiceServer).UpdateMajor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/major.MajorService/UpdateMajor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MajorServiceServer).UpdateMajor(ctx, req.(*UpdateMajorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MajorService_DeleteMajor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMajorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MajorServiceServer).DeleteMajor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/major.MajorService/DeleteMajor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MajorServiceServer).DeleteMajor(ctx, req.(*DeleteMajorReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MajorService_ListMajor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMajorReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MajorServiceServer).ListMajor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/major.MajorService/ListMajor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MajorServiceServer).ListMajor(ctx, req.(*ListMajorReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MajorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "major.MajorService",
	HandlerType: (*MajorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMajor",
			Handler:    _MajorService_CreateMajor_Handler,
		},
		{
			MethodName: "ReadMajor",
			Handler:    _MajorService_ReadMajor_Handler,
		},
		{
			MethodName: "UpdateMajor",
			Handler:    _MajorService_UpdateMajor_Handler,
		},
		{
			MethodName: "DeleteMajor",
			Handler:    _MajorService_DeleteMajor_Handler,
		},
		{
			MethodName: "ListMajor",
			Handler:    _MajorService_ListMajor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "major.proto",
}
