apiVersion: apps/v1
kind: Deployment
metadata:
  name: major-service-api-deployment
  labels:
    app: msp-major-service-grpc-api
spec:
  selector:
    matchLabels:
      app: msp-major-service-grpc-api
  replicas: 1
  template:
    metadata:
      labels:
        app: msp-major-service-grpc-api
    spec:
      containers:
        - name: msp-major-ga
          image: gcr.io/helical-clock-244705/msp-major-service-grpc-api-img:v2.1
          imagePullPolicy: Always
          ports:
            - name: msp-major-a
              containerPort: 9191


---
apiVersion: v1
kind: Service
metadata:
  name: msp-major-service-api
spec:
  selector:
    app: msp-major-service-grpc-api
  ports:
    - name: http
      port: 80
      targetPort: 8181
  type: LoadBalancer
