apiVersion: apps/v1
kind: Deployment
metadata:
  name: major-service-deployment
  labels:
    app: msp-major-service-grpc-server
spec:
  selector:
    matchLabels:
      app: msp-major-service-grpc-server
  replicas: 1
  template:
    metadata:
      labels:
        app: msp-major-service-grpc-server
    spec:
      containers:
        - name: msp-major-gs
          image: gcr.io/helical-clock-244705/msp-major-service-grpc-server-img:v1
          ports:
            - name: msp-major-s
              containerPort: 9191


---
apiVersion: v1
kind: Service
metadata:
  name: msp-major-service
spec:
  selector:
    app: msp-major-service-grpc-server
  ports:
    - port: 9191
      targetPort: msp-major-s
